---
- name: Configure MongoDB
  hosts: db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0

  tasks:
  - name: Change mongo config file
    template:
      src: templates/mongod.conf.j2
      dest: /etc/mongod.conf
      mode: 0644
    notify: restart mongod

  handlers:
  - name: restart mongod
    service: name=mongod state=restarted

- name: Configure APP
  hosts: app
  tags: app-tag
  become: true
  vars:
    db_host: 10.128.0.25

  tasks:
  - name: Add unit file for Puma
    copy:
      src: files/puma.service
      dest: /etc/systemd/system/puma.service
    notify: reload puma.service

  - name: Add config for DB connection
    template:
      src: templates/db_config.j2
      dest: /home/ubuntu/db_config
    tags: app-tag

  - name: enable puma
    systemd: name=puma enabled=yes

  handlers:
  - name: reload  puma
    become: true
    systemd: name=puma state=restarted
    notify: reload puma.service

- name: Deploy App
  hosts: app
  tags: deploy-tag
  become: true

  tasks:
  - name: Install git
    apt:
      name: git
      state: present

  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/ubuntu/reddit
      version: monolith
    notify: restart puma

  - name: bundle install
    bundler:
      state: present
      chdir: /home/ubuntu/reddit

  handlers:
  - name: restart puma
    become: true
    systemd: name=puma state=restarted
